### ISSUE TITLE
on ne peut pas lier des doc à des projets ou acteurs que l'on aurait pas saisi nous meme:

### ISSUE THREAD

**Issue by ninagraveline** [yesiman/INRAE.VINEAS#1]
ll faut corriger pour que tout les contenus déja saisis par d'autres soit accessibles pour n'importe qui pour lié dans le menu déroulant

**Comment by yesiman** [comment]
Bonjour Nina, je crois que cette question a été posée durant la réunion,
c'était un choix qui avait été fait à l'époque avec l'équipe Agrisource de
mémoire.
En gros tu veux que j'affiche tous les projet ou acteurs dans la base pour
effectuer des liaisons et non pas uniquement les données de l'utilisateur
connecté ?
Alors par contre ne pas oublier que les gens du coup pourront effectuer
toutes les liaisons qu'ils souhaitent et ce sans validation.

Le ven. 23 oct. 2020 à 11:49, ninagraveline <notifications@github.com> a
écrit :

**Comment by ninagraveline** [comment]
oui c'est ça. car par ex là j'ai deux rapports que je veux relier à l'umr system que qq'un d'autre (marc surement) a déja saisi et je ne peuxpas le faire.
sinon les gens vont être obligé de saisir deux fois les choses...

**Comment by yesiman** [comment]
Ok je regarde ce point.

Le ven. 23 oct. 2020 à 12:11, ninagraveline <notifications@github.com> a
écrit :

**Comment by yesiman** [comment]
Bonjour Nina,
Ce point doit être modifié en production, dans les relations les
utilisateurs ont dorénavant accès à toute la base.
Bonne journée.
Fabrice

**Comment by ninagraveline** [comment]
merci ça marche
