### ISSUE TITLE
Wrong "HOME" address

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#11]
When clicking "HOME" there is no page associated to this link!

**Comment by MaddyTintinger** [comment]
@yesiman Ceci est valable pour les langues autres que Français et anglais

**Comment by yesiman** [comment]
Je ne comprends pas, je me suis mis en Portuguais, je suis allé sur la
carto , j'ai ensuite cliqué sur accueil (traductible dans les éléments du
menu sinon n'hésites pa à m'envoyer les traductions), mais en cliquant sur
accueil , je suis bien reparti sur la page d'accueil dans il y a bien un
lien associé.
Je pense que je ne fais pas la bonne manipulation pour reproduire l'erreur.

Le mar. 12 janv. 2021 à 19:26, MaddyTintinger <notifications@github.com> a
écrit :

**Comment by eccele** [comment]
The Portuguese version works, the Italian one does not.

Correct address: https://www.vineas.net/it/1/home.html
Non-existing address: https://www.vineas.net/it/it/-1/home.html
(there is a "-" that must be removed).

Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno mar 12 gen 2021 alle ore 17:24 Fabrice GRENOUILLET <
notifications@github.com> ha scritto:

**Comment by slavenIBE** [comment]
I too experienced sometimes that the HOME site for the Italian version does not function because of the '-' that gets added to the adress
![immagine](https://user-images.githubusercontent.com/77341538/104450254-19bee000-55a0-11eb-91df-10709025698d.png)

**Comment by yesiman** [comment]
Thank you yes the Italian link was invalid. It should work now.

**Comment by slavenIBE** [comment]
It does not. I put the hour and date as reference so you may see it persists
![immagine](https://user-images.githubusercontent.com/77341538/104454203-c94a8100-55a5-11eb-8aca-a3def05a02dd.png)
Whenever you click the HOME button it redirects to the wrong page
