### ISSUE TITLE
Mixed languages in solutions

### ISSUE THREAD

**Issue by AlenAlbreht** [yesiman/INRAE.VINEAS#12]
When I go to solutions page of VINEAS and select English from the language bar, there is a mixture of languages (English+French) used in the drop-down menu of "stake"

**Comment by MaddyTintinger** [comment]
This is for the second step of translation. It will be fixed soon

**Comment by eccele** [comment]
I add that in some cases the title and the text are in English, but the sub-title is in French. There is more than one example.

**Comment by MaddyTintinger** [comment]
@AlenAlbreht As we have a dedicated issue for these problems can you close this one please ?
