### ISSUE TITLE
Map of projects and actors - TRANSLATION MISSING

### ISSUE THREAD

**Issue by slavenIBE** [yesiman/INRAE.VINEAS#14]
When accessing the Italian version of the Map of projects and actors there is only the English version of the options

**Comment by slavenIBE** [comment]
![immagine](https://user-images.githubusercontent.com/77341538/104449972-b765df80-559f-11eb-9d12-c6011a615693.png)

**Comment by MaddyTintinger** [comment]
Same as the other comment

**Comment by slavenIBE** [comment]
> 
> 
> Same as the other comment

The same response applies unfortunately

**Comment by MaddyTintinger** [comment]
Hi @slavenIBE, this issue has been half-solved. It is only remaining the "Filtre" problem that I note in a email to Fabrice. Can you please close this issue ?
