### ISSUE TITLE
Contributors term in French on the Italian home-page

### ISSUE THREAD

**Issue by slavenIBE** [yesiman/INRAE.VINEAS#15]
On the Italian version homepage on the last part of the page the term **Contributors** is still in French. Needs to be changed to CONTRIBUTORI

![immagine](https://user-images.githubusercontent.com/77341538/104450778-e7fa4900-55a0-11eb-8246-f74c209e7e48.png)

**Comment by MaddyTintinger** [comment]
It is for the second step of translation (see my email)

**Comment by slavenIBE** [comment]
> 
> 
> It is for the second step of translation (see my email)

I am unable to edit in Dropbox due to insufficient space therefore cannot modify it in the document.

**Comment by MaddyTintinger** [comment]
@slavenIBE Issue solved, can you please close this issue ?
