### ISSUE TITLE
Spanish page not fully translated

### ISSUE THREAD

**Issue by LorenaLorLor** [yesiman/INRAE.VINEAS#16]
Submenus and superior tab are in French. Some submenus are in English.

<img width="1439" alt="Captura de pantalla 2021-01-20 a las 14 07 18" src="https://user-images.githubusercontent.com/63557217/105179597-cf061080-5b29-11eb-9cf8-b8e97e24b8bd.png">

**Comment by MaddyTintinger** [comment]
Hi @LorenaLorLor ,

You need to translate these expressions in the Excel files I mentionned in my email from 15/01 10:55. Did you manage to access the dropbox? I tried to add you. If not, I can directly send you the excel files.

Best,
Maddy

**Comment by LorenaLorLor** [comment]
Hi Maddy. Please, could you send me the Excel files? I can't manage to access to Dropbox because I've got the free plan and the folder is too heavy.

**Comment by MaddyTintinger** [comment]
Hi @LorenaLorLor this issue has been solved, can you please close this issue ?
