### ISSUE TITLE
Import impossible de document depuis la version portugaise

### ISSUE THREAD

**Issue by MaddyTintinger** [yesiman/INRAE.VINEAS#17]
Bonjour Fabrice (@yesiman),

Wilco et Filipa me font remonter qu'ils n'arrivent pas à soumettre de document lorsqu'ils sont en version portugaise... Mais en version anglaise oui... 
L'autre jour j'ai eu des soucis d'import de document aussi quand je mettais une "version en cours" différente de la langue utilisée... Je ne sais pas si cela vient de cela. 
C'est un problème à traiter en priorité pour que tout le monde puisse ajouter du contenu dans sa langue.

Merci,
A plus tard,
Maddy

**Comment by MaddyTintinger** [comment]
Une question soulevée est de quelle heure à quelle heure sont faites les MAJ/mises en prod sur VINEAS, car Wilco travaille souvent vers 22/23h. Est-ce que ça peut être ça qui bloque la mise en ligne ?

Quelle poids max pour les pdf ? Elle n'est pas mise dans les tooltips

**Comment by yesiman** [comment]
Bonjour Maddy,
Non il y a bien un problème sur les documents selon certaines langues. Je
viens de tester le portuguais qui ne fonctionne pas comme le fr, je ne sais
pas trop pourquoi il n'y a rien de spécial sauf que ce sont des langues
ajoutées donc je corrige cela pour ce soir dès que j'ai compris la cause.
A plus tard
Fabrice



Le ven. 22 janv. 2021 à 14:27, MaddyTintinger <notifications@github.com> a
écrit :

**Comment by yesiman** [comment]
Ba non ça marche en portuguais...Je me disais bien il y avait pas de raison.
Peuvent-ils m'envoyer leur document que je teste ?

**Comment by MaddyTintinger** [comment]
Moi ça ne fonctionne pas quand je suis en langue française mais que je sélectionne une version en cours différente du frnaçais (essai avec l'anglais et le portugais)

**Comment by yesiman** [comment]
Ah merci effectivement c'est uniquement quand on switch de langue désolé,
je vais pouvoir corriger, par contre peuvent-ils se connecter en portuguais
pour tester sans switcher de langue ?
Merci

Le ven. 22 janv. 2021 à 14:47, MaddyTintinger <notifications@github.com> a
écrit :

**Comment by MaddyTintinger** [comment]
Wilco a réussi à mettre le document en se connectant en portugais

**Comment by yesiman** [comment]
Merci pour l'information, je suis sur la correction lors du switch.

Le ven. 22 janv. 2021 à 16:05, MaddyTintinger <notifications@github.com> a
écrit :

**Comment by yesiman** [comment]
Mise en ligne de la correction. Encore quelques tests de mon côté mais normalement c'est ok.
