### ISSUE TITLE
Adjustments in "new Actor" form

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#18]
The "Properties" box speaks of moving the properties, but there is no way to do that. Moreovoer, there is no "green pencil". In general, it is not clear the meaning of this box... 

Furthermore:

The text in the "Properties" (which appears in Italian) is not correct.
Correct text:
Le proprietà si riferiscono ai campi che descrivono le tue pagine. In quest'area è possibile gestire le proprietà delle tue pagine. Puoi ordinare le proprietà come desideri con la funzione "drag and drop". Puoi modificare le tue proprietà cliccando sull'icona a matita verde. Si aprirà un pop-up che ti darà accesso a tutte le funzionalità. Se hai i diritti necessari, puoi aggiungere e progettare una nuova proprietà cliccando su "Aggiungi nuova".

In the "guide" pop-up boxes (twice)
 
Agrisource --> VINEAS

Short presentation -->  sub-title 
(the word “presentation” is misleading…)
 
Activity: please add one category, because it is widely represented: “professional studio / consultants”
 
Evenements --> Events

**Comment by eccele** [comment]
(NB: THE WRONG WORDS AND THE PROBLEM WITH THE "PROPERTIES" BOX ARE COMMON TO THE OTHER FORMS

**Comment by eccele** [comment]
Of the original list, one remains unsolved in the English version (not in the Italian one): there is Agrisource instead of VINEAS in Name and in Presentation.

**Comment by MaddyTintinger** [comment]
Done
