### ISSUE TITLE
Adjustments in "News" form

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#20]
See my two previous ones for the common adjustments (properties box, short presentation, guide, "Active" button, keywords...)

Evènements --> Events

Mots clés saisie libre --> What is this? There is already an English field for keywords...

**Comment by eccele** [comment]
Now the problem is only that there are two fields for keywords (I think the first one must be deleted)

**Comment by MaddyTintinger** [comment]
Done
