### ISSUE TITLE
Problème affichage BO

### ISSUE THREAD

**Issue by MaddyTintinger** [yesiman/INRAE.VINEAS#25]
Bonjour Fabrice @yesiman ,

Emanuele ne voit pas la propriété Solution et leviers dans sont BO
![image](https://user-images.githubusercontent.com/72983752/106756723-db14c680-662f-11eb-9d5d-756dfd33e2a8.png)

alors que sur mon compte utilisateur (différent de mon compte admin) je la vois
![image](https://user-images.githubusercontent.com/72983752/106756819-f253b400-662f-11eb-9a70-ffa2922bf2fd.png)
![image](https://user-images.githubusercontent.com/72983752/106756925-10211900-6630-11eb-9fda-1af4a318d26a.png)

**Comment by yesiman** [comment]
Bonjour Maddy,

Peux-tu me donner l'email de cet utilisateur avec lequel il se logue ? Et
sais tu s'il était déjà utilisateur Agrisource ?

Pour lui attribuer les droits dans les profils, directement il est
possible de leur ouvrir l'accès. Je vais le faire dès que je connais son
mail.

Merci

Fabrice

Merci.

Le mer. 3 févr. 2021 à 17:57, MaddyTintinger <notifications@github.com> a
écrit :

**Comment by MaddyTintinger** [comment]
Bonjour Fabrice,

emanuele.eccel@fmach.it 
Je pense qu'il s'était inscrit sur Agrisource car sa date d'inscription est le 8/1/2019

Maddy
