### ISSUE TITLE
Visibility of internet info for actors & Actor form problems

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#3]
When we open an Actor file we don't see any info about:
- URL
- social channels
- email (the latter is also missing in the subscription form, indeed...)

**Problems with Actor form**

About social channels: when e.g. the fb name is input in the Actor form, the form inserts https// by default. This should not happen becase a fb name is not an URL. A more correct suffix for fb would be "https://www.facebook.com/". Same for others.

A field for email is missing: at the moment you can write only to the person who have submitted the form, but this might not be the correct solution (at present, we partners are inserting a lot of forms of other actors). At the foot of the Actor page you can write a message to the person in charge, which should not be the submitter: name and email should be taken from specific fields in the Actor form.

In the Actor form the field "Events" is missing.

In the Actor form the field Keyword should be populated by new submitters, and the full list should be visible. Here we cannot input new entries and the list comes... from where??

**Comment by MaddyTintinger** [comment]
Thank you for your comment, Emanuele. We will see what we can do. 

The field Event is now in the Actor page. 

the keywords were added by Marc. Only administrators can add keywords. There may be a number of keywords that are not translated, I will see if we can translate them via an excel file.

**Comment by MaddyTintinger** [comment]
When the added actor creates an account on the platform, you can give him the rights to modify their page. At this time they will display how referrer and contact person. The actor must create an account to be a referrer.

**Comment by eccele** [comment]
> When the added actor creates an account on the platform, you can give him the rights to modify their page. At this time they will display how referrer and contact person. The actor must create an account to be a referrer.

Sorry, but how can we do this? It is important, because we have created a lot of entries on behalf of actors, which should then manage autonomously their documents.

**Comment by MaddyTintinger** [comment]
> > When the added actor creates an account on the platform, you can give him the rights to modify their page. At this time they will display how referrer and contact person. The actor must create an account to be a referrer.
> 
> Sorry, but how can we do this? It is important, because we have created a lot of entries on behalf of actors, which should then manage autonomously their documents.

I am writing a kind of "User Guide" I can send by the end of the week

**Comment by eccele** [comment]
> the keywords were added by Marc. Only administrators can add keywords. There may be a number of keywords that are not translated, I will see if we can translate them via an excel file.

It is not only a problem of translation: the existing keywords are often useless in the framework of VINEAS, it seems they have been imported from a very differen context. In general, in all the DB I know for documents, keywords can be input by submitters, and in case existing keywords are prompted to avoid duplications. So it should be ascertained:
- if keywords can be input by any submitter, the field should be "free" and it could display the existing ones
- if not, better to remove this field, or in alternative we could write down a number of generic keywords
