### ISSUE TITLE
LIst of referents includes wrong names

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#32]
This is a list of referents for a "solution". The only correct name is the last one: where do the others come from?

![image](https://user-images.githubusercontent.com/9801331/109462496-d7743400-7a63-11eb-9577-c2057b70e053.png)

**Comment by MaddyTintinger** [comment]
It is temprorary. As I give the rgiths to modify to everybody in MEDCLIV, everybody is appearing as referent. As soon as the cards will be translated I will delte this.
