### ISSUE TITLE
Solution title not visible

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#34]
This is the French version; same for the Italian. Fine for the English one! Title:
Adaptation d'un cépage grâce à la variabilité génétique : le clone

![image](https://user-images.githubusercontent.com/9801331/109471633-5459da80-7a71-11eb-8fe2-e2625749ee08.png)

**Comment by eccele** [comment]
This happens also for other pages. E.g. this the "actor" page for FEM. IN English it is ok
![image](https://user-images.githubusercontent.com/9801331/109473813-18744480-7a74-11eb-8f1a-c28c36020763.png)

in **all other languages** the name and address are not fully visible:

![image](https://user-images.githubusercontent.com/9801331/109473905-3477e600-7a74-11eb-8391-737a0e7a7a8c.png)

**Comment by MaddyTintinger** [comment]
Thank you Emanuele. The reason is the length of the menu in the top bar. Fabrice will make the changes
