### ISSUE TITLE
double zoom bar

### ISSUE THREAD

**Issue by ficarlos** [yesiman/INRAE.VINEAS#38]
In the relational map, we can find two zoom bars, but they are not identified as Zoom bar (- <--> +).
And is not clear the exact difference between each other. This needs to be improved for a better user experience. 
![image](https://user-images.githubusercontent.com/73879323/109983586-e0326780-7cfa-11eb-83fb-4bb0936f796d.png)

**Comment by MaddyTintinger** [comment]
Hi @ficarlos, ou can close this issue as it has been solved by adding a legend

**Comment by MaddyTintinger** [comment]
Hi Filipa, You can close this issue as it has been fixed. 
![image](https://user-images.githubusercontent.com/72983752/115842439-1ef0be00-a41e-11eb-97d6-ccffcc246d19.png)
