### ISSUE TITLE
Title not fully readable

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#4]
In opening an "event" I see this:
![image](https://user-images.githubusercontent.com/9801331/102598953-13625300-411d-11eb-9504-0efae14ede5f.png)

Probably the title is too long: in this case, in the field the maximum number of characters should be given. Or better, a different arrangement of the words could be done, because there is a lot of space...

**Comment by MaddyTintinger** [comment]
@yesiman Je te laisse voir cela, l'image d'Emanuele est un évenement 
Et ci-dessous la page acteur du cirad
![image](https://user-images.githubusercontent.com/72983752/103523292-eed7dc00-4e7b-11eb-9c73-a01b873ebe76.png)
Est-ce qu'il fait mettre un nombre limité de caractères pour ne plus avoir ce problème? ou bien alors étendre la zone de texte vers la droite car il y a de la place entre le titre et le bouton précédent...

**Comment by yesiman** [comment]
Bonjour Maddy Meilleurs vœux,
Oui j'élargirai ma zone si besoin, j'ai mis en test la page solution et
leviers et je travaille en priorité sur les ordres d'affichage des données,
(fiche chapeau, tris, languages)
A plus tard bonne journée.
Fabrice

Le lun. 4 janv. 2021 à 14:01, MaddyTintinger <notifications@github.com> a
écrit :

**Comment by MaddyTintinger** [comment]
![image](https://user-images.githubusercontent.com/72983752/105006519-13fd4a80-5a37-11eb-889d-ee1321f1068e.png)
![image](https://user-images.githubusercontent.com/72983752/105006541-1a8bc200-5a37-11eb-8e48-9657e522f99b.png)
Good morning @eccele,
You can close the issue as it is fixed

**Comment by MaddyTintinger** [comment]
@eccele This problem has been fixed (see the previous comment), please can you close it ?
