### ISSUE TITLE
translations missing

### ISSUE THREAD

**Issue by ficarlos** [yesiman/INRAE.VINEAS#40]
There are a number of words that need to be translated. 
Also, some words already in Portuguese need to be adjusted - is there any possibility for the Portuguese team to edit the pages in Portuguese?

![image](https://user-images.githubusercontent.com/73879323/109986378-95feb580-7cfd-11eb-92bd-80e92dc83c24.png)

**Comment by MaddyTintinger** [comment]
The last Excel file will fix this, I will import the Excel file as soon that I have the Slovenian translations ;)

**Comment by MaddyTintinger** [comment]
Hi Filipa, if there is no problem in the current version you can close this issue, Thank you !
![image](https://user-images.githubusercontent.com/72983752/115842860-89096300-a41e-11eb-8948-c9f8a1b723d5.png)
