### ISSUE TITLE
A "property" box is displayed but it is meaningless (?)

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#42]
When adding a new card (any type), the "property" page displays this message:

![image](https://user-images.githubusercontent.com/9801331/110325141-47139180-8017-11eb-8daa-0a47fa49af07.png)

As alredy stated some weeks ago, the meaning of this message is unclear, and there is neither reason nor possibility of moving the "property" fields... I think it has been recycled from other applications.

**Comment by MaddyTintinger** [comment]
I changed it, you can have a look at the Italian translation (translator used) 
![image](https://user-images.githubusercontent.com/72983752/110772017-7581ae80-825b-11eb-831b-8738e95b73e1.png)
![image](https://user-images.githubusercontent.com/72983752/110772099-892d1500-825b-11eb-8dd8-f92d66305f89.png)

**Comment by eccele** [comment]
Ok, thank you. The part that you changed is (I think) in the "solution and
levers". Just a small change in the text:

Una soluzione o una leva per affrontare le sfide del cambiamento climatico
(adattamento o mitigazione) non è ancora descritta sulla piattaforma? Invia
un modulo per descriverlo e quindi invita altri attori e progetti a
mostrare la propria esperienza in questo settore. Questo è il cuore del
networking e della condivisione delle esperienze!

Invia un modulo per descriverlo  --> Compila una scheda che la descriva


Thank you. Sorry for today: it is possible that I can connect at about
15:30 - 16, if you are still there...


Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno gio 11 mar 2021 alle ore 11:19 MaddyTintinger <
***@***.***> ha scritto:
