### ISSUE TITLE
changing the title of the sub-page "Events on the..."

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#44]
In the home page, I can choose to see all the events or scrolling the agenda where I can choose a date. This is a good organization, however, the title of the second possibility is misleading, since it reports the date of today as default. A correct title should be:
"Choose the date" or something similar.

![image](https://user-images.githubusercontent.com/9801331/111440002-3396b380-8706-11eb-84ed-499f23fcfb70.png)

**Comment by MaddyTintinger** [comment]
I cannot change this because I only can modify "event on the" and the date automatically appears

**Comment by eccele** [comment]
Ok, but the wording is a little misleading because it does not communicate
that the user can choose the date. If you simply write, instead of " event
on the": "Search by date:" - and then the date appears -  everything would
be clear, don't you agree?

I have seen that the filtering names have been corrected, good. Just,
please correct this:

[image: image.png]

Finally, in the input forms the names of the filtering categories must be
changed, too. In Italian


Azioni --> Scala d'azione

Domaines techniques --> Aree tecniche

Domaines d'action --> Campo d'azione


Of course, this is a problem for all languages...


Thank you,


Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno lun 22 mar 2021 alle ore 18:51 MaddyTintinger <
***@***.***> ha scritto:
