### ISSUE TITLE
Changing the name of the two types of selection of "Solutions"

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#45]
In the "Solutions and Levers" search page, two possibilities are given:

![image](https://user-images.githubusercontent.com/9801331/111479939-be40d800-8731-11eb-80cb-af2bba2224db.png)

However, these do not match with what is done. The correct names should be something like:

 "Explore by search filters" and "Explore by topic". 

Also, to avoid confusion, a standard shoud be that the leftmost choice is selected by default when a page opens...

**Comment by MaddyTintinger** [comment]
Done
