### ISSUE TITLE
Missing logos

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#47]
The logos of FEM and CIRAD are missing in the foot of VINEAS home page!

**Comment by MaddyTintinger** [comment]
Bonsoir @yesiman, les logos des partenaires MEDCLIV sont bien fixes? 
Peux-tu regarder car les logos de FEM et CIRAD manquent dans cette bannière. 
Merci!

Maddy

**Comment by yesiman** [comment]
Bonjour Maddy,
Les partenaires sont ceux saisis dans les relations (propriété partenaires).
A plus tard.
Fabrice

Le lun. 22 mars 2021 à 21:45, MaddyTintinger ***@***.***> a
écrit :
