### ISSUE TITLE
Solutions and levers: removal of previous selection keys

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#48]
This is not really prioritary, however, it should be fixed sooner or later.

1
When I select some solution cards according to the several keys, I can see the selected key above (eg. picture), in this case GESTIONE DELL'ACQUA

![image](https://user-images.githubusercontent.com/9801331/112118336-8e278800-8bbc-11eb-9bcb-cbcbb970ab78.png)

but then I had selected "All", and the current search is for all, not only for GESTIONE DELL'ACQUA, so the green button should disappear when I select "All" in that key, because this generates confusion.

2
For the same reason, when I select "All" in a key, all the terms should have a tick, not only the one(s) that I had selected before: they remain selected, even if they are no more (see example in this picture).

![image](https://user-images.githubusercontent.com/9801331/112118772-fd04e100-8bbc-11eb-94d4-ef345c961f5d.png)

3
If I choose a category from the list of topics I get a list of solutions. I see the filtering options on top: I can manage them, but have no effect. Since the number of solution cards by topic is never high, I think that a filtering here is useless and it can be deleted. Or made it work...

**Comment by MaddyTintinger** [comment]
Good morning @eccele,
I don't understand your last point, which filter would be useless? 

Bonjour @yesiman, 
Un dysfonctionnment principal concernant la filtration des solutions. 
 si je sélectionne un élément d'une catégorie puis que je remet sur tous, les résultats affichés sont corrects (tous) mais l'élément sélectionné reste sélectionné ce qui est un peu bizarre, il faudrait que lorsqu'on clique sur tous, tout soit coché, ce qui n'est pas le cas même par défaut.

**Comment by eccele** [comment]
I think that further filtering the results of a choice of solution cards,
already done by clicking on the "MORE" button when I choose a "topic" (here
<https://www.vineas.net/en/2_5/solutions_leviers.html>), is not necessary,
since the number of cards displayed is in any case low. So, in my opinion
it can be removed, if it is a problem having it working (at the moment it
is not...).

Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno mer 24 mar 2021 alle ore 10:11 MaddyTintinger <
***@***.***> ha scritto:

**Comment by yesiman** [comment]
Bonjour Maddy,
Quand tout est coché, on peut laisser tout décocher lorsque "tout" est
coché, et effectivement je vais vérifier que lorsque l'on clique sur "tous"
cela supprime bien les préfiltres.

Le mer. 24 mars 2021 à 13:11, MaddyTintinger ***@***.***> a
écrit :

**Comment by MaddyTintinger** [comment]
Hello @eccele
,
Fabrice fixed the issue, you can now close the issue. Thank you
Maddy
