### ISSUE TITLE
Empty category in IMPACTS OF CC

### ISSUE THREAD

**Issue by slavenIBE** [yesiman/INRAE.VINEAS#50]
I noticed the category France, which is empty, in the category of IMPACTS OF CC 
![immagine](https://user-images.githubusercontent.com/77341538/112624721-40b25180-8e2e-11eb-9d04-41c937ae296e.png)
What is the purpose of this subcategory?
![immagine](https://user-images.githubusercontent.com/77341538/112624779-56277b80-8e2e-11eb-91a0-7079c87880bb.png)

**Comment by MaddyTintinger** [comment]
That has been changed, the infographies are now in this sub tab

**Comment by MaddyTintinger** [comment]
HI @slavenIBE, you can close this issue as it has been fixed : 
![image](https://user-images.githubusercontent.com/72983752/115843228-e4d3ec00-a41e-11eb-9363-d314e7df8ea8.png)
![image](https://user-images.githubusercontent.com/72983752/115843240-e7cedc80-a41e-11eb-9de1-60a69a8d1413.png)
Thank you!
