### ISSUE TITLE
Translation issue in SOLUTIONS AND LEVERS

### ISSUE THREAD

**Issue by slavenIBE** [yesiman/INRAE.VINEAS#51]
![immagine](https://user-images.githubusercontent.com/77341538/112625112-c46c3e00-8e2e-11eb-8e3c-737a2ffc93ca.png)
There is an English term that is present in the Italian section that needs to be reomved (highlighted in the red box) and also two grammatical changes that need to be done:

questa --> queste
muncipalità --> municipalità

**Comment by MaddyTintinger** [comment]
Hi Slaven,
I just corrected the mistakes, you can now close the issue. Thank you
Maddy
