### ISSUE TITLE
My name on the referents page for IBE 

### ISSUE THREAD

**Issue by slavenIBE** [yesiman/INRAE.VINEAS#52]
![immagine](https://user-images.githubusercontent.com/77341538/112625757-a18e5980-8e2f-11eb-80bb-3484c4aacfe1.png)

**Comment by MaddyTintinger** [comment]
Bonjour @yesiman, 
voici le problème de nom que je te mentionnais
Bonne journée,
Maddy

**Comment by MaddyTintinger** [comment]
Bonjour Fabrice @yesiman, pourras-tu rechecker ce porblème qui est toujours présent et qui nous a été mentionné il ya un moment maintenant. Merci!

**Comment by yesiman** [comment]
Bonjour Maddy,
On est d'accord qu'il manque Camilla Chieco mais c'est normal que Slaven y
soit ?
Merci.
Fabrice

Le mar. 14 sept. 2021 à 16:39, MaddyTintinger ***@***.***> a
écrit :

**Comment by MaddyTintinger** [comment]
Hello Slaven, 

You can close this issue because it is finally solved :
![image](https://user-images.githubusercontent.com/72983752/135987520-022340d4-d78c-430b-b5ec-5e8e23cb0481.png)

Have a nice day

Maddy
