### ISSUE TITLE
Greece present in map like a partner country

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#55]
At the bottom of Home page Greece is represented as a partner country: it should not.

**Comment by MaddyTintinger** [comment]
Bonjour @yesiman,

Je n'vais pas fait attention avant mais la Grèce est présente sur la carte en page d'accueil alors qu'ils ne font pas parti du projet. 
Pour rappel les pays du projet sont : Portugal, Espagne, France, Italie, Slovénie et Chypre. 
![image](https://user-images.githubusercontent.com/72983752/114031182-694d3900-987b-11eb-80c5-0be987372d83.png)

Merci pour la ocrrection,

Maddy

**Comment by yesiman** [comment]
Bonjour Maddy,

Ok je retire la Grèce je n'avais pas fait attention !!

Bon début de journée.

Fabrice

Le jeu. 8 avr. 2021 à 17:02, MaddyTintinger ***@***.***> a
écrit :
