### ISSUE TITLE
Inappropriate translation in SLO

### ISSUE THREAD

**Issue by AlenAlbreht** [yesiman/INRAE.VINEAS#56]
In the drop-down menu, "LESTVICA DELOVANJA" should be replaced by "NIVO DELOVANJA"

![Screenshot 2021-03-29 19 35 10](https://user-images.githubusercontent.com/77341714/112876698-1c70a200-90c6-11eb-88b9-2169606bff48.png)

**Comment by MaddyTintinger** [comment]
Done

**Comment by AlenAlbreht** [comment]
This issue has not yet been resolved. I just checked. Does it maybe take some time for the corrections to take effect on the page?

**Comment by MaddyTintinger** [comment]
Now it is solved

**Comment by MaddyTintinger** [comment]
Hi @AlenAlbreht, I think that you can close this issue as it has been fixed : 
![image](https://user-images.githubusercontent.com/72983752/115843558-3ed4b180-a41f-11eb-8a4d-b722290e26c7.png)
