### ISSUE TITLE
About vineas tab

### ISSUE THREAD

**Issue by AlenAlbreht** [yesiman/INRAE.VINEAS#57]
The page title still reads "PLATFORMA". It should be replaced by  "VINEAS - KOLABORATIVNA PLATFORMA"

![Screenshot 2021-03-29 21 54 14](https://user-images.githubusercontent.com/77341714/112892220-57c89c00-90d9-11eb-928e-75d458c03272.png)

**Comment by MaddyTintinger** [comment]
Done last Tuesday afternoon
