### ISSUE TITLE
Title needs to be changed (Impact CC)

### ISSUE THREAD

**Issue by AlenAlbreht** [yesiman/INRAE.VINEAS#58]
"Vpliv podnebnih sprememb na vinski in vinski sektor v Sredozemlju" should be changed to "Vpliv podnebnih sprememb na vinski sektor v Sredozemlju"

![Screenshot 2021-03-29 21 57 43](https://user-images.githubusercontent.com/77341714/112892599-cdcd0300-90d9-11eb-925f-ea0e3478be1e.png)

**Comment by MaddyTintinger** [comment]
Done last Tuesday afternoon
