### ISSUE TITLE
Non-automatic links between Actor and Documents

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#6]
I have input some Documents which are linked to the "Player" Fondazione Edmund Mach, but these links do not appear in the relation graphs until I explicit them in the Actor card. Is it possible to make it work with just one entry (eg. in Documents), without the necessity of opening again the Actor card and input the Document? Every new link (e.g. with a News) should force the submitter to open the Actor card to add the relation, and this is undesirable...

**Comment by MaddyTintinger** [comment]
Bonjour Fabrice @yesiman,
Je pense que ce problème n'est pas réglé car je viens d'ajouter le document "Evolutions climatiques: quels impacts pour le Languedoc?". Voici sa carte des relations:
![image](https://user-images.githubusercontent.com/72983752/105188365-1f826b80-5b34-11eb-88a0-1d14bc137dca.png)
Et si je vais sur la page Acteur de l'AOC Languedoc, je ne vois pas le lien avec ce nouveau document:
![image](https://user-images.githubusercontent.com/72983752/105188501-4345b180-5b34-11eb-8de9-87f79c8777fe.png)

A plus tard, 
Maddy

**Comment by yesiman** [comment]
Oui Maddy je discutais avec Monique qui hier m'a remonté ce problème (elle
a géré Agrisource depuis ses débuts) , du coup j'ai passé une bonne partie
de la journée et déboguer cela, en fait lors de la création d'un nouvel
acteur, les relations réciproques (la mise à jour automatique des relations
dans les enfants sélectionnés) ne se faisaient pas.
Je fais encore quelques tests avant mise en ligne dans la soirée.
Fabrice

Le mer. 20 janv. 2021 à 18:29, MaddyTintinger <notifications@github.com> a
écrit :

**Comment by yesiman** [comment]
Ne devrait plus se produire lors de la création

**Comment by MaddyTintinger** [comment]
@eccele this issue have been solved, please can you close it ?
