### ISSUE TITLE
PRIORITARY: problems with Agenda (Events) updating

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#61]
A new event was issued (date: 20th April), but the Agenda does not show it. I think that the items with the closest dates should be visible.

If I look at the list, the sorting (by date, by alphabetic order) do not work. And, again, the lisy is limited to  1o items...

**Comment by MaddyTintinger** [comment]
Bonjour Fabrice @yesiman,

Il y a un problème sur des évènements qui mènent vers une erruer quand on les ouvre depuis la page d'accueil :
"Webinar 20/04/2021 h16..."
"Comment faire de l'écoconception..."

J'ai l'impression que cest dans les autres langues que le français car si je clique depuis le site ne français j'arrive à les ouvrir mais si je me mets en anglais ou en italien non ... 
https://www.vineas.net/en/7_115/6070649980c57a103aee967d/WEBINAR%2020/04/2021%20h16:%20I%20rosati%20nell'era%20del%20climate%20change:%20le%20sfide%20per%20preservare%20aromi%20e%20tipicit%C3%A0.html 

Bonne journée et merci,

Maddy

**Comment by eccele** [comment]
Indeed, I don't see any difference in entering the event in French or in
other languages: the action leads to nowhere.

Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno lun 12 apr 2021 alle ore 16:05 MaddyTintinger <
***@***.***> ha scritto:

**Comment by yesiman** [comment]
Bonjour,
La cause est le point d'interrogation dans le titre, lors de la génération
de l'url le point d'interrogation n'est pas accepté.
Je pourrais pallier cela même si non prévu mais déjà vous pouvez modifier
le titre pour éviter le lien invalide.
Fabrice

**Comment by eccele** [comment]
The problem exists also for other entries, e.g. the new one "WEBINAR
20/04/2021...", which has no question marks.

Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno mar 13 apr 2021 alle ore 06:49 Fabrice GRENOUILLET <
***@***.***> ha scritto:

> Bonjour,
> La cause est le point d'interrogation dans le titre, lors de la génération
> de l'url le point d'interrogation n'est pas accepté.
> Je pourrais pallier cela même si non prévu mais déjà vous pouvez modifier
> le titre pour éviter le lien invalide.
> Fabrice
>

**Comment by yesiman** [comment]
Yes because adding the date in the title "2020/4/2021" with "/" causes bad
url too (invalids parameters). Is there the need adding the event date in
the title ?

**Comment by yesiman** [comment]
I don't know why the event date is not visible but we should display it
with only the event title.

**Comment by eccele** [comment]
Ok, I can ask to avoid using the special characters, but it sounds odd,
indeed. I had asked some weeks ago to have the visibility of the date and
place of the events, because this is important in the Agenda, The only
alternative is including this information in the title...

Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno mar 13 apr 2021 alle ore 08:45 Fabrice GRENOUILLET <
***@***.***> ha scritto:

> I don't know why the event date is not visible but we should display it
> with only the event title.
>
> Le mar. 13 avr. 2021 à 10:43, Fabrice Grenouillet ***@***.***>
> a écrit :
>
> > Yes because adding the date in the title "2020/4/2021" with "/" causes
> bad
> > url too (invalids parameters). Is there the need adding the event date in
> > the title ?
> >

**Comment by yesiman** [comment]
No need to avoid specials chars it should be ok now.

**Comment by eccele** [comment]
Indeed, I have just input a new event (it is a test!) with the date ot
tomorrow. It is not displayed on the home page, just in "see all" or if I
choose the exact day.The events should be displayed in their chronological
order of occurrence, or am I wrong? This does not seem to happen.

Yours,

Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno sab 17 apr 2021 alle ore 14:01 Fabrice GRENOUILLET <
***@***.***> ha scritto:

> No need to avoid specials chars it should be ok now.
>

**Comment by MaddyTintinger** [comment]
Hello @eccele , You did not tick "Active" on the home page, that is why it does not appear

**Comment by eccele** [comment]
Yes, of course, sorry! Thank you,

Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno lun 19 apr 2021 alle ore 09:43 MaddyTintinger <
***@***.***> ha scritto:
