### ISSUE TITLE
One "type of document" is in french

### ISSUE THREAD

**Issue by AlenAlbreht** [yesiman/INRAE.VINEAS#66]
Under documents using SLO language, at the drop-down menu, there is one type of document still not translated into SLO - "Cours - Formations"
![image](https://user-images.githubusercontent.com/77341714/131739239-64984f78-7c9f-4b89-91dc-c33fd88dcdf3.png)

**Comment by MaddyTintinger** [comment]
Hello Alen,

The type of document has not been updated since the last changes, it will be done in the week. Thank you

**Comment by MaddyTintinger** [comment]
Hello Alen, This has been solved too, you can close the ticket
Thank you for your involvement
