### ISSUE TITLE
Homepage, "DNEVNI RED" - EVENTS

### ISSUE THREAD

**Issue by AlenAlbreht** [yesiman/INRAE.VINEAS#67]
In SLO language there is "DNEVNI RED" at the EVENTS part of the main VINEAS page.  "DNEVNI RED" should be rephrased into "KOLEDAR DOGODKOV".
![image](https://user-images.githubusercontent.com/77341714/131741333-dafe1b28-e526-4fd0-8e0f-88b054b5153a.png)

**Comment by MaddyTintinger** [comment]
Hi Alen,

I just change this, you can close this ticket.

Thank you
