### ISSUE TITLE
Profile page not entirely translated

### ISSUE THREAD

**Issue by AlenAlbreht** [yesiman/INRAE.VINEAS#68]
When I updated my profile in the new profile form online, I noticed that the red button in the bottom most area of the page is not translated into Slovene (or English when using ENG language) and it says "desinscription".
![image](https://user-images.githubusercontent.com/77341714/135806879-2a02034e-a3d3-4e27-b770-275e8de6ad35.png)

**Comment by MaddyTintinger** [comment]
This has been solved too, you can close the ticket. Thank you
