### ISSUE TITLE
Problème coming events

### ISSUE THREAD

**Issue by MaddyTintinger** [yesiman/INRAE.VINEAS#7]
Bonjour Fabrice @yesiman ,

Filipa me fait remonter le problème qu'elle a ajouté un évènement qui était du 01/12/2020 jusqu'au 10/01/2021. Dans ce cas là il ne s'affichait pas dans les coming events. Pour essayer de le faire afficher j'ai modifié la date pour qu'il soit du 10/01/2021 au 10/01/2021 mais il ne s'affiche toujours pas dans les coming events même s'il apparait bien dans le calendrier... 
![image](https://user-images.githubusercontent.com/72983752/103672085-12824b80-4f7c-11eb-8258-a1f47cefcb5b.png)
![image](https://user-images.githubusercontent.com/72983752/103672120-275edf00-4f7c-11eb-9ca2-961cf7d09118.png)
Le 2ème évènement à venir se passe en mai donc celui de Filipa devrait s'afficher avant... 

Bonne soirée,
Maddy

**Comment by yesiman** [comment]
Bonjour Maddy,

Donc c'est lié au fait que je n'ai pas encore mis en production la remontée
des 6 événements (actuellement 4) car on devait finaliser solutions et
leviers d'abord, je finalise l'annuaire global et on pourra discuter d'une
mise en ligne/production si tu veux. Par contre je m'aperçois que du coup
les événements devraient être triés dans un ordre différent : du plus
récent au plus ancien or j'ai l'impression que c'est le contraire je te
laisse me dire ce que tu en penses.

A plus tard bonne journée.

Fabrice

Le mar. 5 janv. 2021 à 20:35, MaddyTintinger <notifications@github.com> a
écrit :

**Comment by MaddyTintinger** [comment]
Bonjour Fabrice,
D'accord, quand tu penses être bon pour mettre prod, envoie moi un message pour qu'on s'appelle pour voir tout cela. J epense que Nina sera aussi intéressée si on s'appelle avant la mise ne prod. 
Concernant l'ordre des évènements, il me semble correct. Dans l'annuaire, ils sont du plus récent au plus ancien, et dans les coming event, ça a l'air de fonctionner. A moins que je rate quelque chose.

A plus tard, bonne journée,
Maddy
