### ISSUE TITLE
Agora post writing

### ISSUE THREAD

**Issue by AlenAlbreht** [yesiman/INRAE.VINEAS#71]
Why is the "deadline" field in the Agora post manadatory? I propose that this field is marked optional since not all Agora postings have a deadline.
![image](https://user-images.githubusercontent.com/77341714/135808680-1b2f08e1-20e3-47a6-9155-0a36b758ab26.png)

**Comment by AlenAlbreht** [comment]
Also, for the "description" window, language switching is not working. So if I want to make an Agora post that will be visible in ENG and also in SLO, I cannot do that. Only one language version can be used for all languages, regardless of the language you choose in the top most dropdown menu.

**Comment by MaddyTintinger** [comment]
We decided that the deadline field is mandatory because we don't want to have obsolete posts in the agora.

Regarding the translation, I added the quick way to translate.

**Comment by MaddyTintinger** [comment]
I think you can close the issue
