### ISSUE TITLE
Missing "actor" to be linked

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#8]
CREA is subscribed as an Actor. However, when I try to input this actor in a Document file (as a "related player") CREA is not found!

Please, I recall to change player --> actor in the form, thank you!

**Comment by yesiman** [comment]
If you type CREA in the "related players" field, it should show a
"Consiglio per la ricerca in agricoltura e l'analisi dell'economia agraria"
record. It is the CREA actor but we display the title and not the acronyme
in the results.
