### ISSUE TITLE
Problème interne upload de document

### ISSUE THREAD

**Issue by MaddyTintinger** [yesiman/INRAE.VINEAS#9]
Bonjour Fabrice @yesiman ,

Wilco, un collègue en stage au Portugal, me fait remonté qu'il a voulu uploader un document ce matin et que cela n'a pas fonctionné du premier coup. A la première soumission, il ya eu un messaged'erreur; La page s'est créée avec ce message. Il a ensuite de nouveau soumis le document et cela a fonctionné. Donc il existe 2 pages avec le même nom dans le FO:

- Une page avec un message d'erreur:

https://www.vineas.net/en/7_102/5ffb8f9b2d4c7a0c0cca74d6/An%20overview%20of%20climate%20change%20impacts%20on%20European%20viticulture.html

- Une page correcte:

https://www.vineas.net/en/7_102/5ffc1b7b2d4c7a0c0cca7b19/An%20overview%20of%20climate%20change%20impacts%20on%20European%20viticulture.html

Dans le BO, il n'a la visibilité sur une seule fiche donc impossible de supprimer celle avec le message d'erreur.
![image](https://user-images.githubusercontent.com/72983752/104168338-33c0bd00-53fe-11eb-91d8-eedc5e53b2e9.png)

Dans le BO administrateur je peux supprimer cette page avec erreur mais je la laisse pour le moment, si tu veux regarder ce qu'il s'est passé. En triant par "date descendante" la fiche la plus récente avec "FCT Nova" dans related players est la page qui fonctionne, l'autre est celle avec l'erreur. 

A plus tard,

Maddy

**Comment by yesiman** [comment]
Bonjour Maddy,
Sais tu quel message d'erreur il a eu ?
Merci
